/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Test2RouteImport } from './routes/Test2'
import { Route as TestRouteImport } from './routes/Test'
import { Route as PackagesRouteImport } from './routes/Packages'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as IndexRouteImport } from './routes/index'

const Test2Route = Test2RouteImport.update({
  id: '/Test2',
  path: '/Test2',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/Test',
  path: '/Test',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/Packages',
  path: '/Packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/Packages': typeof PackagesRoute
  '/Test': typeof TestRoute
  '/Test2': typeof Test2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/Packages': typeof PackagesRoute
  '/Test': typeof TestRoute
  '/Test2': typeof Test2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/Packages': typeof PackagesRoute
  '/Test': typeof TestRoute
  '/Test2': typeof Test2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Contact' | '/Packages' | '/Test' | '/Test2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Contact' | '/Packages' | '/Test' | '/Test2'
  id: '__root__' | '/' | '/Contact' | '/Packages' | '/Test' | '/Test2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRoute
  TestRoute: typeof TestRoute
  Test2Route: typeof Test2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Test2': {
      id: '/Test2'
      path: '/Test2'
      fullPath: '/Test2'
      preLoaderRoute: typeof Test2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Test': {
      id: '/Test'
      path: '/Test'
      fullPath: '/Test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Packages': {
      id: '/Packages'
      path: '/Packages'
      fullPath: '/Packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRoute,
  TestRoute: TestRoute,
  Test2Route: Test2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
